package component:usb@0.2.1;

interface events {
    use usb.{usb-device};

    variant device-connection-event {
        pending,
        connected(usb-device),
        disconnected(usb-device)
    }

    // TODO: wasip3 will support async functions and streams
    update: func() -> device-connection-event;
}
