package component:usb@0.2.1;

interface types {
    enum endpoint-direction {
        in,
        out,
    }

    enum endpoint-transfer-type {
        control,
        isochronous,
        bulk,
        interrupt,
    }

    enum endpoint-sync-type {
        no-sync,
        %async,
        adaptive,
        synchronous,
    }

    enum endpoint-usage-type {
        data,
        feedback,
        feedback-data,
        reserved,
    }

    record version {
        major: u8,
        minor: u8,
        subminor: u8,
    }

    enum speed {
        unknown,
        low,
        full,
        high,
        super,
        superplus,
    }

    enum device-handle-error {
        invalid-param,
        timeout,
        pipe,
        overflow,
        no-device,
        io,
    }

    type duration = u64;

    variant primary-language {
        afrikaans,
        albanian,
        arabic,
        armenian,
        assamese,
        azeri,
        basque,
        belarussian,
        bengali,
        bulgarian,
        burmese,
        catalan,
        chinese,
        croatian,
        czech,
        danish,
        dutch,
        english,
        estonian,
        faeroese,
        farsi,
        finnish,
        french,
        georgian,
        german,
        greek,
        gujarati,
        hebrew,
        hindi,
        hungarian,
        icelandic,
        indonesian,
        italian,
        japanese,
        kannada,
        kashmiri,
        kazakh,
        konkani,
        korean,
        latvian,
        lithuanian,
        macedonian,
        malay,
        malayalam,
        manipuri,
        marathi,
        nepali,
        norwegian,
        oriya,
        polish,
        portuguese,
        punjabi,
        romanian,
        russian,
        sanskrit,
        serbian,
        sindhi,
        slovak,
        slovenian,
        spanish,
        sutu,
        swahili,
        swedish,
        tamil,
        tatar,
        telugu,
        thai,
        turkish,
        ukrainian,
        urdu,
        uzbek,
        vietnamese,
        hid,
        other(u16),
    }

    variant sub-language {
        standard,
        classic,
        traditional,
        modern,
        algeria,
        argentina,
        australia,
        austria,
        bahrain,
        belgium,
        belize,
        bokmal,
        bolivia,
        brazil,
        brunei-darussalam,
        canada,
        caribbean,
        chile,
        china,
        colombia,
        costa-rica,
        cyrillic,
        dominican-republic,
        ecuador,
        egypt,
        el-salvador,
        finland,
        guatemala,
        honduras,
        hong-kong,
        india,
        iraq,
        ireland,
        jamaica,
        johab,
        jordan,
        kuwait,
        latin,
        lebanon,
        libya,
        liechtenstein,
        luxembourg,
        macau,
        malaysia,
        mexico,
        monaco,
        morocco,
        netherlands,
        new-zealand,
        nicaragua,
        nynorsk,
        oman,
        pakistan,
        panama,
        paraguay,
        peru,
        philippines,
        puerto-rico,
        qatar,
        saudi-arabia,
        singapore,
        south-africa,
        switzerland,
        syria,
        taiwan,
        trinidad,
        tunisia,
        united-arab-emirates,
        united-kingdom,
        united-states,
        uruguay,
        venezuela,
        yemen,
        zimbabwe,
        usage-data-descriptor,
        vendor-defined1,
        vendor-defined2,
        vendor-defined3,
        vendor-defined4,
        other(u16),
    }

    record language {
        id: u16,
        primary-language: primary-language,
        sub-language: sub-language,
    }

}